from contextlib import contextmanager
import os
from pathlib import Path
import sqlite3
import re


DATABASE_PATH = Path(
    os.environ.get("SURVEY_DATABASE_PATH", Path(__file__).with_name("survey.db"))
)


class PostgresConnection:
    """The existing SQLite-style query API, backed by a persistent Postgres DB.

    Queries are application-owned SQL; values always remain bound parameters.
    Only identity declarations, REAL precision and parameter markers differ.
    """
    def __init__(self, connection):
        self.connection = connection

    def execute(self, sql, parameters=()):
        if sql.strip().upper() == 'BEGIN IMMEDIATE':
            # Preserve the serialized read/check/write operations used by C1.
            # Transaction-scoped locks also work with Neon's transaction pooler.
            return self.connection.execute('SELECT pg_advisory_xact_lock(20261009324)')
        sql = sql.replace('INTEGER PRIMARY KEY AUTOINCREMENT', 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
        sql = re.sub(r'\bREAL\b', 'DOUBLE PRECISION', sql)
        return self.connection.execute(sql.replace('?', '%s'), parameters)

    def executescript(self, sql):
        self.execute('BEGIN IMMEDIATE')
        for statement in sql.split(';'):
            if statement.strip():
                self.execute(statement)


class PostgresRow(dict):
    def __getitem__(self, key):
        return list(self.values())[key] if isinstance(key, int) else super().__getitem__(key)


def postgres_row_factory(cursor):
    names = [column.name for column in cursor.description] if cursor.description else []
    return lambda values: PostgresRow(zip(names, values))


@contextmanager
def get_connection():
    url = os.environ.get('SURVEY_DATABASE_URL', '')
    if url:
        import psycopg
        connection = psycopg.connect(url, row_factory=postgres_row_factory, connect_timeout=15)
        exposed = PostgresConnection(connection)
    else:
        if os.environ.get('RENDER') == 'true':
            raise RuntimeError('Set SURVEY_DATABASE_URL on Render; its free filesystem cannot retain SQLite responses')
        connection = sqlite3.connect(DATABASE_PATH)
        connection.row_factory = sqlite3.Row
        exposed = connection
    try:
        yield exposed
        connection.commit()
    except Exception as error:
        connection.rollback()
        if url and isinstance(error, psycopg.IntegrityError):
            raise sqlite3.IntegrityError(str(error)) from error
        raise
    finally:
        connection.close()


def initialize_database() -> None:
    with get_connection() as connection:
        connection.executescript(
            """
            CREATE TABLE IF NOT EXISTS sessions (
                session_id TEXT PRIMARY KEY,
                participant_id TEXT NOT NULL,
                study_id TEXT NOT NULL,
                trial_order TEXT NOT NULL,
                current_index INTEGER NOT NULL DEFAULT 0,
                started_at TEXT NOT NULL,
                completed_at TEXT
            );

            -- Kept for compatibility with the original pilot database.
            CREATE TABLE IF NOT EXISTS responses (
                response_id INTEGER PRIMARY KEY AUTOINCREMENT,
                participant_id TEXT NOT NULL,
                session_id TEXT NOT NULL,
                trial_id INTEGER NOT NULL,
                sample_id TEXT NOT NULL,
                trial_order INTEGER NOT NULL,
                issue_type TEXT NOT NULL,
                quality_rating INTEGER NOT NULL,
                comment TEXT NOT NULL DEFAULT '',
                play_count INTEGER NOT NULL,
                started_at TEXT NOT NULL,
                submitted_at TEXT NOT NULL,
                UNIQUE(session_id, trial_id)
            );

            CREATE TABLE IF NOT EXISTS study_responses (
                response_id INTEGER PRIMARY KEY AUTOINCREMENT,
                participant_id TEXT NOT NULL,
                session_id TEXT NOT NULL,
                study_id TEXT NOT NULL,
                trial_id TEXT NOT NULL,
                sample_id TEXT NOT NULL,
                trial_order INTEGER NOT NULL,
                answers_json TEXT NOT NULL,
                play_counts_json TEXT NOT NULL,
                started_at TEXT NOT NULL,
                submitted_at TEXT NOT NULL,
                UNIQUE(session_id, trial_id)
            );
            """
        )
